In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [123]:
client_df=pd.read_csv("Client_Data.csv")

In [124]:
client_df

Name  Gender  Spend_Amt    Company  Client_Id    Domain
0     Aman Verma    Male       1000     Zomato        101      food
1     Aman Verma    Male        400     Zomato        101      food
2     Aman Verma    Male        350     Zomato        101      food
3     Aman Verma    Male       1500     Zomato        101      food
4     Aman Verma    Male       2000  Uber Eats        101      food
5     Aman Verma    Male        150  Uber Eats        101      food
6     Aman Verma    Male        800  Uber Eats        101      food
7     Aman Verma    Male        290      DoDev        101    Gaming
8     Aman Verma    Male       1200       Robu        101    Gaming
9   Rakesh Singh    Male       2000      Dodev        102    Gaming
10  Rakesh Singh    Male       1000     Game4U        102    Gaming
11  Rakesh Singh    Male        200   Yolo Inc        102    Gaming
12  Rakesh Singh    Male        300      DoDev        102    Gaming
13  Rakesh Singh    Male        400      DoDev        102    Gaming
14  Rakesh Singh    Male        600      DoDev        102    Gaming
15  Shruti Patel  Female       1000      Nykaa        103  cosmetic
16  Shruti Patel  Female       1000  Keya Seth        103  cosmetic
17  Shruti Patel  Female       1000     Zomato        103      food

In [125]:
client_df.shape

(18, 6)

In [126]:
client_df["Name"].value_counts()

Name
Aman Verma      9
Rakesh Singh    6
Shruti Patel    3
Name: count, dtype: int64

In [127]:
client_df.drop(["Spend_Amt","Company"],axis=1,inplace=True)

In [128]:
client_df.head()

Name Gender  Client_Id Domain
0  Aman Verma   Male        101   food
1  Aman Verma   Male        101   food
2  Aman Verma   Male        101   food
3  Aman Verma   Male        101   food
4  Aman Verma   Male        101   food

In [129]:
client_df["Gender"].value_counts()

Gender
Male      15
Female     3
Name: count, dtype: int64

In [130]:
client_df["Domain"].value_counts()

Domain
food        8
Gaming      8
cosmetic    2
Name: count, dtype: int64

In [131]:
client_df["Gender"]=client_df["Gender"].map({"Male":1,"Female":0})

In [132]:
client_df["Domain"]=client_df["Domain"].map({"food":0,"Gaming":1,"cosmetic":2})

In [133]:
client_df.head()

Name  Gender  Client_Id  Domain
0  Aman Verma       1        101       0
1  Aman Verma       1        101       0
2  Aman Verma       1        101       0
3  Aman Verma       1        101       0
4  Aman Verma       1        101       0

In [134]:
client_df["Name"]=client_df["Name"].map({"Aman Verma":0,"Rakesh Singh":1,"Shruti Patel":2})

In [135]:
client_df.head()

Name  Gender  Client_Id  Domain
0     0       1        101       0
1     0       1        101       0
2     0       1        101       0
3     0       1        101       0
4     0       1        101       0

In [136]:
feature=client_df.drop(["Domain"],axis=1)
feature.head()

Name  Gender  Client_Id
0     0       1        101
1     0       1        101
2     0       1        101
3     0       1        101
4     0       1        101

In [137]:
target=client_df.iloc[:,-1:]
target.head()

Domain
0       0
1       0
2       0
3       0
4       0

In [138]:
from sklearn.linear_model import LogisticRegression 
model_offers = LogisticRegression() 
model_offers.fit(feature, target)

C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [139]:
model_offers.score(feature,target)

0.8333333333333334

In [140]:
!pip install xgboost


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [141]:
from xgboost import XGBClassifier
# fit model no training data
model_xgb_offers = XGBClassifier()
model_xgb_offers.fit(feature,target)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [142]:
model_xgb_offers.score(feature,target)*100

83.33333333333334

In [143]:
model_xgb_offers.predict(feature)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2], dtype=int64)

In [144]:
target

Domain
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        1
8        1
9        1
10       1
11       1
12       1
13       1
14       1
15       2
16       2
17       0

In [145]:
model_xgb_offers.predict([[0,1,101]])

array([0], dtype=int64)

In [146]:
model_xgb_offers.predict([[1,1,102]])

array([1], dtype=int64)

In [147]:
model_xgb_offers.predict([[2,0,103]])

array([2], dtype=int64)

In [148]:
from joblib import dump

In [153]:
dump(model_xgb_offers,'./../savemodels/offersPredict.joblib')

['./../savemodels/offersPredict.joblib']